# Generated by the GKE Cluster Portal — do not edit by hand.
# Re-submit the portal form to regenerate this file.

module "gke" {
  source = "../../terraform/cluster"
  project_id = "projectkjn"
  cluster_name = "xyasd"
  region = "us-west1"
  node_locations = [
    "us-west1-a",
    "us-west1-b",
    "us-west1-c"
  ]
  environment = "dev"
  blueprint = "standard"
  owner_group = "anshumansingh0523@gmail.com"
  platform_admin_group = "anshumansingh0523@gmail.com"
  gke_security_group = "anshumansingh0523@gmail.com"
  technical_contact = "anshumansingh0523@gmail.com"
  iam_principal_type = "group"
  enable_google_groups_rbac = true
  system_machine_type = "e2-standard-4"
  general_machine_type = "n2-standard-8"
  capacity = {
    system_min_nodes = 1
    system_max_nodes = 3
    general_min_nodes = 1
    general_max_nodes = 5
    max_pods_per_node = 32
  }
  network = {
    mode = "create"
    network_name = "gke-network"
    create_nat = true
    private_endpoint_only = false
    authorized_cidrs = [
      "0.0.0.0/0"
    ]
    node_cidr = "10.0.0.0/24"
    pod_cidr = "10.4.0.0/14"
    service_cidr = "10.8.0.0/20"
    control_plane_cidr = "172.16.0.0/28"
    subnet_name = "snet-xyasd-9a9a9c"
    pod_range_name = "pods-xyasd-9a9a9c"
    service_range_name = "svc-xyasd-9a9a9c"
  }
  gpu = {
    enabled = false
    model = "nvidia-h100-80gb"
    machine_type = "a3-highgpu-8g"
    accelerator_count = 8
    minimum_nodes = 0
    maximum_nodes = 2
    zones = []
    provisioning_model = "standard"
    reservation_name = null
  }
  backup = {
    tier = "none"
    retention_days = 7
    delete_lock_days = 0
    target_rpo_minutes = 60
    include_volume_data = true
    include_secrets = true
  }
  deletion_protection = true
  release_channel = "REGULAR"
  labels = {
    environment = "dev"
    "managed-by" = "gke-cluster-portal"
  }
}
