# Generated by scripts/render_gke_tf.py — do not edit by hand.
# Regenerate from the source cluster request YAML instead.

module "gke" {
  source = "TODO-SET-GKE-MODULE-SOURCE"

  project_id = "gcpproject-490711"
  cluster_name = "new-demo"
  region = "us-west1"
  node_locations = [
    "us-west1-a",
    "us-west1-b",
    "us-west1-c"
  ]
  environment = "dev"
  blueprint = "standard-dev-v1"
  system_machine_type = "e2-standard-4"
  general_machine_type = "n2-standard-4"
  capacity = {
    system_min_nodes = 3
    system_max_nodes = 6
    general_min_nodes = 0
    general_max_nodes = 12
    max_pods_per_node = 64
  }
  network = {
    mode = "dedicated"
    host_project_id = "gcpproject-490711"
    network_name = "gke-platform"
    create_nat = true
    private_endpoint_only = true
    node_cidr = "10.64.0.0/24"
    pod_cidr = "10.128.0.0/16"
    service_cidr = "172.20.0.0/20"
    control_plane_cidr = "172.24.0.0/28"
    subnet_name = "snet-new-demo-07abd5"
    pod_range_name = "pods-new-demo-07abd5"
    service_range_name = "svc-new-demo-07abd5"
  }
  deletion_protection = true
  release_channel = "REGULAR"
  labels = {
    application = "test-team"
    "data-classification" = "internal"
    environment = "dev"
    team = "test-team"
    "cost-center" = "cc-personal-test"
    "managed-by" = "gke-cluster-factory"
  }
}
